hostname: "127.0.0.1"
port: 9000
db:
  hostname: "db"
  port: 3306
  name: "training"
  username: "root"
  password: ""
cors:
  allow:
    origin: "http://localhost:3000"
jwt:
  secret: "hmacSampleSecret"
  issuer: "issuer"
