definitions:
  controller.GetPostsResponse:
    properties:
      posts:
        items:
          $ref: '#/definitions/entity.Post'
        type: array
    type: object
  controller.SignInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  controller.SignUpRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  entity.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  entity.HelloWorld:
    properties:
      lang:
        type: string
      message:
        type: string
    type: object
  entity.Post:
    properties:
      body:
        type: string
      favorites_count:
        type: integer
      id:
        type: string
      is_my_favorite:
        type: boolean
      parent:
        $ref: '#/definitions/entity.Post'
      replies_count:
        type: integer
      user:
        $ref: '#/definitions/entity.User'
    type: object
  entity.User:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      profile:
        type: string
    type: object
info:
  contact: {}
  description: training-app-2023-team2
  title: training-app-2023-team2
  version: "1.0"
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: get helloWorld message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.HelloWorld'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: get helloWorld message
      tags:
      - HelloWorld
  /posts:
    get:
      consumes:
      - application/json
      parameters:
      - description: limit
        in: query
        name: limit
        type: string
      - description: offset
        in: query
        name: offset
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetPostsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: 投稿一覧取得API
      tags:
      - Post
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 画像ファイル
        in: formData
        name: file
        type: file
      - in: formData
        name: content
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: 投稿作成API
      tags:
      - Post
  /posts/{postId}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 投稿ID
        in: path
        name: postId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: NoContent
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: 投稿削除API
      tags:
      - Post
    get:
      consumes:
      - application/json
      description: get post by id
      parameters:
      - description: 投稿ID
        in: path
        name: postId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Post'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: 投稿取得API
      tags:
      - Post
  /posts/{postId}/favorites:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 投稿ID
        in: path
        name: postId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: いいね削除API
      tags:
      - Favorite
    post:
      consumes:
      - application/json
      parameters:
      - description: 投稿ID
        in: path
        name: postId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: いいね作成API
      tags:
      - Favorite
  /posts/{postId}/replies:
    get:
      consumes:
      - application/json
      parameters:
      - description: 投稿ID
        in: path
        name: postId
        required: true
        type: string
      - description: limit
        in: query
        name: limit
        type: string
      - description: offset
        in: query
        name: offset
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetPostsResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: リプライ一覧取得API
      tags:
      - Post
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 投稿ID
        in: path
        name: postId
        required: true
        type: string
      - description: 画像ファイル
        in: formData
        name: file
        type: file
      - in: formData
        name: content
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: リプライ作成API
      tags:
      - Post
  /sign_in:
    post:
      consumes:
      - application/json
      parameters:
      - description: ユーザーログインリクエスト
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: ユーザーログインAPI
      tags:
      - User
  /sign_out:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: ユーザーログアウトAPI
      tags:
      - User
  /sign_up:
    post:
      consumes:
      - application/json
      parameters:
      - description: ユーザー登録リクエスト
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: ユーザー登録API
      tags:
      - User
  /users/{userId}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ユーザーID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: ユーザー取得API
      tags:
      - User
  /users/me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: ログインユーザー取得API
      tags:
      - User
  /users/me/profile:
    put:
      consumes:
      - multipart/form-data
      parameters:
      - in: formData
        name: profile
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: プロフィール更新API
      tags:
      - User
swagger: "2.0"
